version: 2.1

jobs:
  hello-world:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hello from yato"

workflows:
  version: 2
  basic_workflow:
    jobs:
      - hello-world
